### ISSUE TITLE
Implement A Custom Artisan Command

### ISSUE THREAD

**Issue by JoeBocock** [JoeBocock/knockt#12]
Implement an example of a custom Artisan command within the context of a Vending Machine.

[See documentation here.](https://laravel.com/docs/8.x/artisan)

**Comment by accu-clw** [comment]
As an idea, maybe a command to correct stock in a slot (in case someone was lucky and got a double drop!)

**Comment by JoeBocock** [comment]
> As an idea, maybe a command to correct stock in a slot (in case someone was lucky and got a double drop!)

@accu-clw Thanks for the idea! It's been implemented 😄
